sudo: false
language: go
go:
  - 1.5
  - 1.6
  - tip

env:
  - PATH=/home/travis/gopath/bin:$PATH

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mitchellh/gox

script:
  - go vet $(go list ./... | grep -v vendor)
  - go test $(go list ./... | grep -v '/vendor/')
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "cli-unit_{{.OS}}_{{.Arch}}" -osarch="linux/amd64"
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "cli-unit_{{.OS}}_{{.Arch}}" -osarch="linux/386"
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "cli-unit_{{.OS}}_{{.Arch}}" -osarch="darwin/amd64"
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "cli-unit_{{.OS}}_{{.Arch}}" -osarch="darwin/386"
  - gzip cli-unit_linux_amd64
  - gzip cli-unit_linux_386
  - gzip cli-unit_darwin_amd64
  - gzip cli-unit_darwin_386
  - mkdir -p dist release
  - cp cli-unit_linux_amd64.gz dist/cli-unit_linux_amd64_latest.gz
  - cp cli-unit_linux_386.gz dist/cli-unit_linux_386_latest.gz
  - cp cli-unit_darwin_amd64.gz dist/cli-unit_darwin_amd64_latest.gz
  - cp cli-unit_darwin_386.gz dist/cli-unit_darwin_386_latest.gz
  - cp cli-unit_linux_amd64.gz release/cli-unit_linux_amd64_$(git describe --tags).gz
  - cp cli-unit_linux_386.gz release/cli-unit_linux_386_$(git describe --tags).gz
  - cp cli-unit_darwin_amd64.gz release/cli-unit_darwin_amd64_$(git describe --tags).gz
  - cp cli-unit_darwin_386.gz release/cli-unit_darwin_386_$(git describe --tags).gz

deploy:
  - provider: s3
    access_key_id: AKIAJWN36CZNBCQXFFTQ
    secret_access_key:
      secure: "N2csSegpcTwWQDz97p35uQ0FMpydLoAmiusBJMeigANADo6F4BJJZtLx/4rYoF3IVyUrRkvQoMJ5uhbuT/jYSl8ks3v+5x4AfpTR3Qtj1e0ZlMocJ5WG0pjedNGOTq0Nf7jK54RcoGTMMSVW76k2zRhFfjDEhOc5qklD/SKdxS0="
    bucket: dl.fligl.io
    skip_cleanup: true
    local-dir: dist
    upload-dir: artifacts/cli-unit
    acl: public_read
  - provider: s3
    access_key_id: AKIAJWN36CZNBCQXFFTQ
    secret_access_key:
      secure: "N2csSegpcTwWQDz97p35uQ0FMpydLoAmiusBJMeigANADo6F4BJJZtLx/4rYoF3IVyUrRkvQoMJ5uhbuT/jYSl8ks3v+5x4AfpTR3Qtj1e0ZlMocJ5WG0pjedNGOTq0Nf7jK54RcoGTMMSVW76k2zRhFfjDEhOc5qklD/SKdxS0="
    bucket: dl.fligl.io
    skip_cleanup: true
    local-dir: release
    upload-dir: artifacts/cli-unit
    acl: public_read
    on:
      tags: true
